export default {
  docs: [
    // Public product docs
    {
      type: 'category',
      label: 'User Guides',
      items: [{ type: 'autogenerated', dirName: 'user-guides' }],
    },

    // Engineering docs (sequential)
    {
      type: 'category',
      label: 'Developer Docs',
      items: [
        {
          type: 'category',
          label: '01 – Overview',
          items: [
            'overview/project-overview',
            'adr/architecture',
          ],
        },
        {
          type: 'category',
          label: '02 – Data & Access',
          items: [
            'overview/permissions',
          ],
        },
        {
          type: 'category',
          label: '03 – Local Development',
          items: [
            'developer/getting-started-dev',
            'developer/local-env',
            'developer/hasura',
          ],
        },
        {
          type: 'category',
          label: '04 – CI/CD & Docs',
          items: [
            'developer/ci-cd',
            'developer/docs-ops',
          ],
        },
        {
          type: 'category',
          label: '05 – Import & Data Tools',
          items: [
            'csv/README',
          ],
        },
        {
          type: 'category',
          label: 'Checklists',
          items: [
            'overview/bootstrap-checklist',
            'overview/checklists/permissions-update-delete',
            'overview/checklists/ui-mvp-dashboard',
            'overview/checklists/seed-data',
            'overview/checklists/docs-custom-domain',
          ],
        },
        'overview/roadmap',
      ],
    },
  ],
}

