export default {
  docs: [
    {
      type: 'category',
      label: 'User Guides',
      items: [
        { type: 'autogenerated', dirName: 'user-guides' },
      ],
    },
    {
      type: 'category',
      label: 'Developer Docs',
      items: [
        { type: 'autogenerated', dirName: 'overview' },
        { type: 'autogenerated', dirName: 'adr' },
        { type: 'autogenerated', dirName: 'csv' },
      ],
    },
  ],
}

