import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Auto-generated sidebar configuration
// This file is automatically generated by the sync-docs script
// Do not edit manually - changes will be overwritten

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      "type": "doc",
      "id": "intro",
      "label": "Introduction"
},
    {
      type: 'category',
      label: 'Core Documentation',
      items: [
        'data-dictionary',
      ],
    },
    {
      type: 'category',
      label: 'Project Documentation',
      items: [
        'api',
        'project-overview',
        'roadmap',
      ],
    },
    {
      type: 'doc',
      id: 'development',
      label: 'Development Guide',
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        'development/current-status',
        'development/feature-development',
      ],
    },
  ],
};

export default sidebars;
