import fs from 'fs/promises';
import path from 'path';

async function addDocusaurusFrontmatter(filePath, sidebarPosition) {
  try {
    const content = await fs.readFile(filePath, 'utf8');
    
    // Check if frontmatter already exists
    if (content.startsWith('---')) {
      // Update existing frontmatter
      const frontmatterEnd = content.indexOf('---', 3);
      if (frontmatterEnd !== -1) {
        const existingFrontmatter = content.substring(0, frontmatterEnd + 3);
        const restOfContent = content.substring(frontmatterEnd + 3);
        
        // Check if sidebar_position already exists
        if (existingFrontmatter.includes('sidebar_position:')) {
          return; // Already has frontmatter, skip
        }
        
        // Add sidebar_position to existing frontmatter
        const updatedFrontmatter = existingFrontmatter.replace('---', `---\nsidebar_position: ${sidebarPosition}`);
        await fs.writeFile(filePath, updatedFrontmatter + restOfContent);
      }
    } else {
      // Add new frontmatter
      const frontmatter = `---
sidebar_position: ${sidebarPosition}
---

`;
      await fs.writeFile(filePath, frontmatter + content);
    }
  } catch (error) {
    console.error(`Error adding frontmatter to ${filePath}:`, error);
  }
}

async function generateSidebarConfig(docsDir) {
  try {
    const items = await fs.readdir(docsDir, { withFileTypes: true });
    
    // Define document categories and their organization
    const categories = {
      introduction: [],
      core: [],
      project: [],
      development: [],
      other: []
    };
    
    // Sort items: directories first, then files
    const sortedItems = items.sort((a, b) => {
      if (a.isDirectory() && !b.isDirectory()) return -1;
      if (!a.isDirectory() && b.isDirectory()) return 1;
      return a.name.localeCompare(b.name);
    });
    
    for (const item of sortedItems) {
      if (item.isDirectory()) {
        // Handle subdirectories
        const subDir = path.join(docsDir, item.name);
        const subItems = await fs.readdir(subDir);
        const subMarkdownFiles = subItems
          .filter(file => file.endsWith('.md'))
          .map(file => file.replace('.md', ''))
          .sort();
        
        if (subMarkdownFiles.length > 0) {
          const categoryLabel = item.name.charAt(0).toUpperCase() + item.name.slice(1);
          categories.development.push({
            type: 'category',
            label: categoryLabel,
            items: subMarkdownFiles.map(file => `${item.name}/${file}`),
          });
        }
      } else if (item.name.endsWith('.md')) {
        // Handle root markdown files
        const docId = item.name.replace('.md', '');
        const label = docId.charAt(0).toUpperCase() + docId.slice(1).replace(/-/g, ' ');
        
        // Categorize documents
        if (docId === 'intro') {
          categories.introduction.push({
            type: 'doc',
            id: docId,
            label: 'Introduction',
          });
        } else if (docId === 'data-dictionary') {
          categories.core.push({
            type: 'doc',
            id: docId,
            label: 'Data Dictionary',
          });
        } else if (['project-overview', 'roadmap', 'api'].includes(docId)) {
          categories.project.push({
            type: 'doc',
            id: docId,
            label: label,
          });
        } else if (docId === 'development') {
          categories.development.unshift({
            type: 'doc',
            id: docId,
            label: 'Development Guide',
          });
        } else {
          categories.other.push({
            type: 'doc',
            id: docId,
            label: label,
          });
        }
      }
    }
    
    // Build the final sidebar structure
    const sidebarItems = [
      ...categories.introduction,
      ...categories.core,
      ...categories.project,
      ...categories.development,
      ...categories.other
    ];
    
    return sidebarItems;
  } catch (error) {
    console.error('Error generating sidebar config:', error);
    return [];
  }
}

async function generateSidebarsFile(sidebarItems) {
  // Create category sections
  const introSection = sidebarItems.filter(item => item.id === 'intro');
  const coreSection = sidebarItems.filter(item => item.id === 'data-dictionary');
  const projectSection = sidebarItems.filter(item => 
    ['project-overview', 'roadmap', 'api'].includes(item.id)
  );
  const developmentSection = sidebarItems.filter(item => 
    item.id === 'development' || (item.type === 'category' && item.label === 'Development')
  );
  
  const sidebarsContent = `import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Auto-generated sidebar configuration
// This file is automatically generated by the sync-docs script
// Do not edit manually - changes will be overwritten

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
${introSection.length > 0 ? `    ${JSON.stringify(introSection[0], null, 6)},` : ''}
${coreSection.length > 0 ? `    {
      type: 'category',
      label: 'Core Documentation',
      items: [
        'data-dictionary',
      ],
    },` : ''}
${projectSection.length > 0 ? `    {
      type: 'category',
      label: 'Project Documentation',
      items: [
${projectSection.map(item => `        '${item.id}',`).join('\n')}
      ],
    },` : ''}
${developmentSection.length > 0 ? developmentSection.map(item => 
  item.type === 'category' ? `    {
      type: 'category',
      label: '${item.label}',
      items: [
${item.items.map(subItem => `        '${subItem}',`).join('\n')}
      ],
    },` : `    {
      type: 'doc',
      id: '${item.id}',
      label: '${item.label}',
    },`
).join('\n') : ''}
  ],
};

export default sidebars;
`;

  return sidebarsContent;
}

async function syncDocs() {
  try {
    const sourceDir = 'docs';
    const targetDir = 'docs-site/docs';
    
    console.log('🔄 Syncing documentation from docs/ to docs-site/docs/...');
    
    // Ensure target directory exists
    await fs.mkdir(targetDir, { recursive: true });
    
    // Read all files from source directory
    const files = await fs.readdir(sourceDir);
    
    // Filter for markdown files
    const markdownFiles = files.filter(file => file.endsWith('.md'));
    
    // Copy each markdown file
    for (const file of markdownFiles) {
      const sourcePath = path.join(sourceDir, file);
      const targetPath = path.join(targetDir, file);

      await fs.copyFile(sourcePath, targetPath);
      console.log(`  ✅ Copied: ${file}`);
      
      // Add Docusaurus frontmatter if needed
      const docId = file.replace('.md', '');
      if (docId === 'intro') {
        await addDocusaurusFrontmatter(targetPath, 1);
      } else if (docId === 'data-dictionary') {
        await addDocusaurusFrontmatter(targetPath, 1);
      } else if (docId === 'project-overview') {
        await addDocusaurusFrontmatter(targetPath, 1);
      } else if (docId === 'roadmap') {
        await addDocusaurusFrontmatter(targetPath, 2);
      } else if (docId === 'api') {
        await addDocusaurusFrontmatter(targetPath, 3);
      } else if (docId === 'development') {
        await addDocusaurusFrontmatter(targetPath, 1);
      }
    }

    // Handle subdirectories (like development/)
    const items = await fs.readdir(sourceDir, { withFileTypes: true });
    for (const item of items) {
      if (item.isDirectory()) {
        const subSourceDir = path.join(sourceDir, item.name);
        const subTargetDir = path.join(targetDir, item.name);
        
        // Ensure target subdirectory exists
        await fs.mkdir(subTargetDir, { recursive: true });
        
        // Read subdirectory files
        const subFiles = await fs.readdir(subSourceDir);
        const subMarkdownFiles = subFiles.filter(file => file.endsWith('.md'));
        
        for (const file of subMarkdownFiles) {
          const sourcePath = path.join(subSourceDir, file);
          const targetPath = path.join(subTargetDir, file);
          
          await fs.copyFile(sourcePath, targetPath);
          console.log(`  ✅ Copied: ${item.name}/${file}`);
          
          // Add Docusaurus frontmatter for subdirectory files
          const docId = file.replace('.md', '');
          if (item.name === 'development') {
            if (docId === 'current-status') {
              await addDocusaurusFrontmatter(targetPath, 1);
            } else if (docId === 'feature-development') {
              await addDocusaurusFrontmatter(targetPath, 2);
            }
          }
        }
      }
    }
    
    // Also copy any SVG files (like ERD)
    const svgFiles = files.filter(file => file.endsWith('.svg'));
    for (const file of svgFiles) {
      const sourcePath = path.join(sourceDir, file);
      const targetPath = path.join(targetDir, file);
      
      await fs.copyFile(sourcePath, targetPath);
      console.log(`  ✅ Copied: ${file}`);
    }
    
    // Generate and write sidebar configuration
    console.log('🔄 Generating sidebar configuration...');
    const sidebarItems = await generateSidebarConfig(sourceDir);
    const sidebarsContent = await generateSidebarsFile(sidebarItems);
    
    await fs.writeFile('docs-site/sidebars.ts', sidebarsContent);
    console.log('  ✅ Generated: sidebars.ts');
    
    console.log(`✅ Documentation sync complete! ${markdownFiles.length + svgFiles.length} files synced.`);
    
  } catch (error) {
    console.error('❌ Error syncing documentation:', error);
    process.exit(1);
  }
}

syncDocs(); 